version: '3'

services:
  weconnectmqtt:
    image: "tillsteinbach/weconnect-mqtt:latest"
    restart: unless-stopped
    environment:
      - USER=my@vwid-user.de
      - PASSWORD=myvwidpassword
      - BROKER_ADDRESS=mosquitto

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - mosquitto-conf:/mosquitto/config

volumes:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf: