name: Upload Python Package and Docker Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.0'

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v3.1.0
        with:
          images: |
            tillsteinbach/weconnect-mqtt
            ghcr.io/tillsteinbach/weconnect-mqtt
          tags: |
            type=edge
            type=semver,pattern={{version}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      - name: Setup Cache for buildx
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-weconnect-mqtt-${{ github.sha }}
      - name: Login to DockerHub
        #if: (github.event_name == 'push' && (contains(github.ref, '/heads/main') || contains(github.ref, '/tags/v')))
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        #if: (github.event_name == 'push' && (contains(github.ref, '/heads/main') || contains(github.ref, '/tags/v')))
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          context: docker
          #push: (github.event_name == 'push' && (contains(github.ref, '/heads/main') || contains(github.ref, '/tags/v')))
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
